const nodemailer = require('nodemailer')
const dns = require('dns')
require('dotenv').config()

// 🔥 Force IPv4 (Fixes ENETUNREACH on Render)
dns.setDefaultResultOrder('ipv4first')

const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 587,              // Use 587 instead of 465
  secure: false,          // false for 587
  requireTLS: true,
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASS,
  },
})

module.exports = transporter

const sendRoadmapEmail = async ({ to, userName, role, pdfBuffer }) => {
  await transporter.sendMail({
    from:    process.env.EMAIL_FROM,
    to,
    subject: `Your ${role} Roadmap is ready — RoutePilot`,
    html: `
      <div style="font-family:Arial,sans-serif;background:#0a0f14;color:#e2e8f0;max-width:560px;margin:0 auto">
        <div style="background:linear-gradient(135deg,#0d1520,#0a0f14);padding:40px;border-bottom:1px solid #1e2a36;text-align:center">
          <div style="font-size:12px;font-weight:700;color:#00c97a;letter-spacing:0.1em;text-transform:uppercase;margin-bottom:12px">RoutePilot</div>
          <div style="font-size:22px;font-weight:700;color:#f1f5f9;letter-spacing:-0.04em;margin-bottom:4px">Your roadmap is ready</div>
          <div style="font-size:15px;color:#00c97a">${role}</div>
        </div>
        <div style="padding:32px 40px">
          <div style="font-size:15px;color:#94a3b8;margin-bottom:16px">Hey ${userName} 👋</div>
          <div style="font-size:14px;color:#64748b;line-height:1.7;margin-bottom:24px">
            Your personalized <strong style="color:#f1f5f9">${role}</strong> career roadmap
            has been generated by Gemini AI and is attached as a PDF.<br><br>
            Open it, save it, and refer back to it every single day.
          </div>
          <div style="text-align:center">
            <a href="${process.env.FRONTEND_URL}/dashboard"
              style="display:inline-block;padding:12px 28px;background:#00c97a;color:#000;font-weight:700;font-size:14px;border-radius:9px;text-decoration:none">
              View on RoutePilot →
            </a>
          </div>
        </div>
        <div style="padding:0 40px 28px;font-size:11px;color:#334155;text-align:center">
          © ${new Date().getFullYear()} RoutePilot · <a href="${process.env.FRONTEND_URL}" style="color:#00c97a">routepilot.app</a>
        </div>
      </div>
    `,
    attachments: [{
      filename:    `${role.replace(/\s+/g, '-')}-Roadmap-RoutePilot.pdf`,
      content:     pdfBuffer,
      contentType: 'application/pdf',
    }],
  })
}

module.exports = { sendRoadmapEmail }